### ISSUE TITLE
Vapoursynth-global variables not defined

### ISSUE THREAD

**Issue by benny10033** [shinchiro/mpv-winbuild-cmake#54]
I am using the latest build: 20180110 with portable python3.6.4 and vaporsynth portable r41. 

When I try to use mpv with svpflow with a semi-custom script, the video flow couldn't be initialized as the "display_fps" and "video_in" variables are not defined.

```
C:\Users\user\Downloads\Software\mpv>mpv "blah.webm"
Playing: blah.webm
 (+) Video --vid=1 (*) (vp8 480x360 1000.000fps)
 (+) Audio --aid=1 (*) (vorbis 2ch 44100Hz)
Opening video filter: [vapoursynth file=scripts/sample_vs.py]
[ao/wasapi] Error initializing device: AUDCLNT_E_BUFFER_SIZE_NOT_ALIGNED (0x88890019)
[ao/wasapi] This appears to require a weird Windows 7 hack. Retrying.
AO: [wasapi] 44100Hz stereo 2ch s32
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: name 'video_in' is not defined
[vapoursynth]
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src\cython\vapoursynth.pyx", line 1841, in vapoursynth.vpy_evaluateScript
[vapoursynth]   File "scripts/sample_vs.py", line 11, in <module>
[vapoursynth]     clip = video_in
[vapoursynth] NameError: name 'video_in' is not defined
[vapoursynth]
Video filter chain:
  [in] 480x360 yuv420p bt.601/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264
  [vapoursynth] "vapoursynth.00" 480x360 yuv420p bt.601/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264   <---
  [out] ???
Cannot initialize video filters.
Could not initialize video chain.
Video: no video
^C 00:00:01 / 00:07:16 (0%)
```

**Comment by shinchiro** [comment]
Use Vapoursynth **r40**
